export const contentDataModels = {
   Category: {
      name: 'Category',
      dbName: null,
      fields: [
         {
            name: 'id',
            dbName: '_id',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'String',
            default: {
               name: 'auto',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'parentId',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'status',
            kind: 'enum',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'AvailableStatus',
            default: 'Drafted',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'name',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'path',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'description',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'createdAt',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'DateTime',
            default: {
               name: 'now',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'updatedAt',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'DateTime',
            isGenerated: false,
            isUpdatedAt: true,
         },
         {
            name: 'author',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'editor',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'posts',
            kind: 'object',
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Post',
            relationName: 'CategoryToPost',
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
         },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
   },
   Post: {
      name: 'Post',
      dbName: null,
      fields: [
         {
            name: 'id',
            dbName: '_id',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'String',
            default: {
               name: 'auto',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'categoryId',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'category',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Category',
            relationName: 'CategoryToPost',
            relationFromFields: ['categoryId'],
            relationToFields: ['id'],
            relationOnDelete: 'Cascade',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'status',
            kind: 'enum',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'AvailableStatus',
            default: 'Drafted',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'name',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'path',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'imageUrl',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'description',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'metadata',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Metadata',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'createdAt',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'DateTime',
            default: {
               name: 'now',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'updatedAt',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'DateTime',
            isGenerated: false,
            isUpdatedAt: true,
         },
         {
            name: 'author',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'editor',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'postsTags',
            kind: 'object',
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'PostTag',
            relationName: 'PostToPostTag',
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
         },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
   },
   Tag: {
      name: 'Tag',
      dbName: null,
      fields: [
         {
            name: 'id',
            dbName: '_id',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'String',
            default: {
               name: 'auto',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'status',
            kind: 'enum',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'AvailableStatus',
            default: 'Drafted',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'name',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'createdAt',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'DateTime',
            default: {
               name: 'now',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'updatedAt',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'DateTime',
            isGenerated: false,
            isUpdatedAt: true,
         },
         {
            name: 'author',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'editor',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'postsTags',
            kind: 'object',
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'PostTag',
            relationName: 'PostTagToTag',
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
         },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
   },
   PostTag: {
      name: 'PostTag',
      dbName: null,
      fields: [
         {
            name: 'id',
            dbName: '_id',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'String',
            default: {
               name: 'auto',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'postId',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'post',
            kind: 'object',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Post',
            relationName: 'PostToPostTag',
            relationFromFields: ['postId'],
            relationToFields: ['id'],
            relationOnDelete: 'Cascade',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'tagId',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'tag',
            kind: 'object',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Tag',
            relationName: 'PostTagToTag',
            relationFromFields: ['tagId'],
            relationToFields: ['id'],
            relationOnDelete: 'Cascade',
            isGenerated: false,
            isUpdatedAt: false,
         },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
   },
   Comment: {
      name: 'Comment',
      dbName: null,
      fields: [
         {
            name: 'id',
            dbName: '_id',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'String',
            default: {
               name: 'auto',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'status',
            kind: 'enum',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'CommentStatus',
            default: 'Pending',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'post',
            kind: 'object',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'PostLike',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'message',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'createdAt',
            kind: 'scalar',
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: 'DateTime',
            default: {
               name: 'now',
               args: [],
            },
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'updatedAt',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'DateTime',
            isGenerated: false,
            isUpdatedAt: true,
         },
         {
            name: 'author',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'editor',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'User',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'parentId',
            kind: 'scalar',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: 'String',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'parent',
            kind: 'object',
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Comment',
            relationName: 'NestedComment',
            relationFromFields: ['parentId'],
            relationToFields: ['id'],
            relationOnDelete: 'NoAction',
            isGenerated: false,
            isUpdatedAt: false,
         },
         {
            name: 'children',
            kind: 'object',
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: 'Comment',
            relationName: 'NestedComment',
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
         },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
   },
};
