export const CLASS_PROPERTIES: string = '__CLASS_PROPERTIES__';
export const INIT_PARENT_PROPERTIES = '__INIT_PARENT_PROPERTIES__';
export const NO_CACHE_KEY = 'NO_CACHE_KEY';
export const CACHE_WITH_PREFIX_USER_ID_KEY = 'CACHE_WITH_PREFIX_USER_ID_KEY';
